### ISSUE TITLE
Segfault in dhvani_init()

### ISSUE THREAD

**Issue by mohan43u** [tshrinivasan/dhvani-tts#11]
Hi Prasanna,

I'm getting segfault in current master branch. I think following change may be the root cause,

https://github.com/tshrinivasan/dhvani-tts/commit/f14b2aa47c4176e01fe4ab37531fdeca7dd4dc5a#diff-575156469577900f86c2fec89111c250

Please take a look.

**Comment by prasannatsm** [comment]
Yes segfault occurs. I added j = split(tmp) again but still dhvani segfaults. Will debug it further. If you get any clue in the mean time please let me know.

**Comment by prasannatsm** [comment]
I am not able to revert this commit. Can you please revert?

**Comment by mohan43u** [comment]
Lets see what I can do in the weekend. Not sure we can revert, we just have to fix it.in the current branch.

**Comment by prasannatsm** [comment]
I have fixed the crash. Please pull the master and test. It works for me fine and thanks for reporting :+1: :).
